create_temp_password:
  target:
    entity:
      domain: lock
      integration: tuya_smart_lock
  fields:
    code:
      required: true
      selector:
        text:
    name:
      required: true
      selector:
        text:
    duration_hours:
      required: true
      selector:
        number:
          min: 1
          max: 720
